image: composer/satis
before_script:
- eval $(ssh-agent -s)
- echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
- mkdir -p ~/.ssh
- chmod 700 ~/.ssh
- echo "$GITLAB_HOST_KEY" > ~/.ssh/known_hosts
pages:
    stage: build
    script:
    - /satis/bin/satis build satis.json public
    artifacts:
        paths:
        - public
    only:
    - master
